-- MySQL Script generated by MySQL Workbench
-- Sun May 18 17:06:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tu_huella_ceramica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tu_huella_ceramica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tu_huella_ceramica` DEFAULT CHARACTER SET utf8mb4 ;
USE `tu_huella_ceramica` ;

-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`employee` (
  `idEmployee` INT(11) NOT NULL,
  `role` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmployee`),
  CONSTRAINT `employee_ibfk_1`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `tu_huella_ceramica`.`user` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`administrator` (
  `idAdmin` INT(11) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  CONSTRAINT `administrator_ibfk_1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `tu_huella_ceramica`.`employee` (`idEmployee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`customer` (
  `idCustomer` INT(11) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `billingAddress` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idCustomer`),
  CONSTRAINT `customer_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `tu_huella_ceramica`.`user` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`order` (
  `idOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `idCustomer` INT(11) NULL DEFAULT NULL,
  `products` TEXT NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `deliveryAddress` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `order_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `tu_huella_ceramica`.`customer` (`idCustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`shopping_cart` (
  `idShoppingCart` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrder` INT(11) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idShoppingCart`),
  UNIQUE INDEX `idOrder` (`idOrder` ASC) VISIBLE,
  CONSTRAINT `shopping_cart_ibfk_1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `tu_huella_ceramica`.`order` (`idOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`category` (
  `idCategory` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`product` (
  `idProduct` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `category` INT(11) NULL DEFAULT NULL,
  `isCustom` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `category` (`category` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`category`)
    REFERENCES `tu_huella_ceramica`.`category` (`idCategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`cart_item` (
  `idItemCart` INT(11) NOT NULL AUTO_INCREMENT,
  `idShoppingCart` INT(11) NULL DEFAULT NULL,
  `idProduct` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `subtotal` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idItemCart`),
  INDEX `idShoppingCart` (`idShoppingCart` ASC) VISIBLE,
  INDEX `idProduct` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `cart_item_ibfk_1`
    FOREIGN KEY (`idShoppingCart`)
    REFERENCES `tu_huella_ceramica`.`shopping_cart` (`idShoppingCart`),
  CONSTRAINT `cart_item_ibfk_2`
    FOREIGN KEY (`idProduct`)
    REFERENCES `tu_huella_ceramica`.`product` (`idProduct`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`customer_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`customer_product` (
  `idCustomer` INT(11) NOT NULL,
  `idProduct` INT(11) NOT NULL,
  PRIMARY KEY (`idCustomer`, `idProduct`),
  INDEX `idProduct` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `customer_product_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `tu_huella_ceramica`.`customer` (`idCustomer`),
  CONSTRAINT `customer_product_ibfk_2`
    FOREIGN KEY (`idProduct`)
    REFERENCES `tu_huella_ceramica`.`product` (`idProduct`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`payment` (
  `idPayment` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrder` INT(11) NULL DEFAULT NULL,
  `idCustomer` INT(11) NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `paymentMethod` VARCHAR(50) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idPayment`),
  UNIQUE INDEX `idOrder` (`idOrder` ASC) VISIBLE,
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `tu_huella_ceramica`.`customer` (`idCustomer`),
  CONSTRAINT `payment_ibfk_2`
    FOREIGN KEY (`idOrder`)
    REFERENCES `tu_huella_ceramica`.`order` (`idOrder`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tu_huella_ceramica`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tu_huella_ceramica`.`invoice` (
  `idInvoice` INT(11) NOT NULL AUTO_INCREMENT,
  `idPayment` INT(11) NULL DEFAULT NULL,
  `discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `issueDate` DATE NULL DEFAULT NULL,
  `tax` DECIMAL(10,2) NULL DEFAULT NULL,
  `totalAmount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idInvoice`),
  UNIQUE INDEX `idPayment` (`idPayment` ASC) VISIBLE,
  CONSTRAINT `invoice_ibfk_1`
    FOREIGN KEY (`idPayment`)
    REFERENCES `tu_huella_ceramica`.`payment` (`idPayment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
