-- MySQL Script generated by MySQL Workbench
-- Corregido para utf8mb4_general_ci

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tu_huella_ceramica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tu_huella_ceramica`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE `tu_huella_ceramica`;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email` (`email`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee` (
  `idEmployee` INT(11) NOT NULL,
  `role` VARCHAR(50) NULL,
  PRIMARY KEY (`idEmployee`),
  FOREIGN KEY (`idEmployee`) REFERENCES `user` (`idUser`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administrator` (
  `idAdmin` INT(11) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  FOREIGN KEY (`idAdmin`) REFERENCES `employee` (`idEmployee`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `idCustomer` INT(11) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `billingAddress` TEXT NULL,
  PRIMARY KEY (`idCustomer`),
  FOREIGN KEY (`idCustomer`) REFERENCES `user` (`idUser`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `idOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `idCustomer` INT(11) NULL,
  `products` TEXT NULL,
  `total` DECIMAL(10,2) NULL,
  `date` DATE NULL,
  `deliveryAddress` TEXT NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`idOrder`),
  INDEX (`idCustomer`),
  FOREIGN KEY (`idCustomer`) REFERENCES `customer` (`idCustomer`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_cart` (
  `idShoppingCart` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrder` INT(11) NULL,
  `total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idShoppingCart`),
  UNIQUE INDEX (`idOrder`),
  FOREIGN KEY (`idOrder`) REFERENCES `order` (`idOrder`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category` (
  `idCategory` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idCategory`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `idProduct` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `price` DECIMAL(10,2) NULL,
  `stock` INT(11) NULL,
  `category` INT(11) NULL,
  `isCustom` TINYINT(1) NULL,
  PRIMARY KEY (`idProduct`),
  INDEX (`category`),
  FOREIGN KEY (`category`) REFERENCES `category` (`idCategory`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cart_item` (
  `idItemCart` INT(11) NOT NULL AUTO_INCREMENT,
  `idShoppingCart` INT(11) NULL,
  `idProduct` INT(11) NULL,
  `quantity` INT(11) NULL,
  `subtotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idItemCart`),
  INDEX (`idShoppingCart`),
  INDEX (`idProduct`),
  FOREIGN KEY (`idShoppingCart`) REFERENCES `shopping_cart` (`idShoppingCart`),
  FOREIGN KEY (`idProduct`) REFERENCES `product` (`idProduct`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `customer_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer_product` (
  `idCustomer` INT(11) NOT NULL,
  `idProduct` INT(11) NOT NULL,
  PRIMARY KEY (`idCustomer`, `idProduct`),
  INDEX (`idProduct`),
  FOREIGN KEY (`idCustomer`) REFERENCES `customer` (`idCustomer`),
  FOREIGN KEY (`idProduct`) REFERENCES `product` (`idProduct`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment` (
  `idPayment` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrder` INT(11) NULL,
  `idCustomer` INT(11) NULL,
  `amount` DECIMAL(10,2) NULL,
  `paymentMethod` VARCHAR(50) NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`idPayment`),
  UNIQUE INDEX (`idOrder`),
  INDEX (`idCustomer`),
  FOREIGN KEY (`idCustomer`) REFERENCES `customer` (`idCustomer`),
  FOREIGN KEY (`idOrder`) REFERENCES `order` (`idOrder`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invoice` (
  `idInvoice` INT(11) NOT NULL AUTO_INCREMENT,
  `idPayment` INT(11) NULL,
  `discount` DECIMAL(10,2) NULL,
  `issueDate` DATE NULL,
  `tax` DECIMAL(10,2) NULL,
  `totalAmount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idInvoice`),
  UNIQUE INDEX (`idPayment`),
  FOREIGN KEY (`idPayment`) REFERENCES `payment` (`idPayment`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- Restaurar configuración
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;